#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Test document conversion functionality
.DESCRIPTION
    Creates a test Markdown file and converts it to various formats
#>

[CmdletBinding()]
param()

$testDir = Join-Path $PSScriptRoot ".." "test_output"
New-Item -ItemType Directory -Path $testDir -Force | Out-Null

$convertScript = Join-Path $PSScriptRoot "convert.ps1"
$checkScript = Join-Path $PSScriptRoot "check_deps.ps1"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Document Converter Test Suite" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check dependencies first
Write-Host "1. Checking dependencies..." -ForegroundColor Yellow
& $checkScript
Write-Host ""

# Create test Markdown file
$testMd = Join-Path $testDir "test_document.md"
@'
# 测试文档 (Test Document)

This is a test document for **Document Converter** skill.

## Features

- Multi-language support (English/中文/한국어)
- PDF generation via LaTeX
- Graceful fallback

## Company Info

**STARLING CO., LIMITED**
香港椋鸟科技有限公司

| Item | Value |
|------|-------|
| Product | Toluene |
| Price | USD 1,100/MT |

---

*Generated by doc-converter skill*
'@ | Out-File -FilePath $testMd -Encoding UTF8

Write-Host "2. Created test file: $testMd" -ForegroundColor Green
Write-Host ""

# Test 1: Markdown to DOCX
Write-Host "3. Testing Markdown → DOCX..." -ForegroundColor Yellow
$testDocx = Join-Path $testDir "test_document.docx"
try {
    & $convertScript -InputFile $testMd -OutputFile $testDocx
    if (Test-Path $testDocx) {
        Write-Host "   ✓ DOCX generated: $testDocx" -ForegroundColor Green
    }
} catch {
    Write-Host "   ✗ Failed: $_" -ForegroundColor Red
}
Write-Host ""

# Test 2: Markdown to HTML
Write-Host "4. Testing Markdown → HTML..." -ForegroundColor Yellow
$testHtml = Join-Path $testDir "test_document.html"
try {
    & $convertScript -InputFile $testMd -OutputFile $testHtml
    if (Test-Path $testHtml) {
        Write-Host "   ✓ HTML generated: $testHtml" -ForegroundColor Green
    }
} catch {
    Write-Host "   ✗ Failed: $_" -ForegroundColor Red
}
Write-Host ""

# Test 3: Markdown to PDF (if LaTeX available)
Write-Host "5. Testing Markdown → PDF..." -ForegroundColor Yellow
try {
    $xelatex = Get-Command xelatex -ErrorAction Stop
    $testPdf = Join-Path $testDir "test_document.pdf"
    & $convertScript -InputFile $testMd -OutputFile $testPdf -PdfEngine xelatex
    if (Test-Path $testPdf) {
        Write-Host "   ✓ PDF generated: $testPdf" -ForegroundColor Green
    }
} catch {
    Write-Host "   ⚠️  XeLaTeX not available, skipping PDF test" -ForegroundColor Yellow
    Write-Host "   To enable PDF: Install TinyTeX or MiKTeX" -ForegroundColor Cyan
}
Write-Host ""

# Summary
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Test Complete" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Test output directory: $testDir" -ForegroundColor White
Write-Host ""

# List generated files
$generatedFiles = Get-ChildItem $testDir -Filter "test_document.*"
if ($generatedFiles) {
    Write-Host "Generated files:" -ForegroundColor Green
    foreach ($file in $generatedFiles) {
        $size = [math]::Round($file.Length / 1KB, 2)
        Write-Host "  - $($file.Name) (${size} KB)"
    }
} else {
    Write-Host "No files generated" -ForegroundColor Yellow
}
